# These are supported funding model platforms

github: [agm024, SarthakPatil-Tech]
patreon: mypatreonusername
open_collective: mycollective
ko_fi: mykofiusername
tidelift: npm/my-package
community_bridge: my-project-name
liberapay: myliberapayusername
issuehunt: myissuehuntusername
lfx_crowdfunding: my-lfx-project
polar: mypolarusername
buy_me_a_coffee: mybmcusername
thanks_dev: mythanksdevusername
custom:
  - https://example.com/donate
  - https://anotherexample.com/support
